server {
    listen 80;
    server_name _;
    # HiddenGame Unity Build
    location ^~ /HiddenGame/ {
        alias /home/phil/projects/HiddenGame/client/;
        index index.html;
        try_files $uri $uri/ /HiddenGame/index.html;

        # Unity WebGL gzip compression headers
        location ~ \.wasm\.gz$ {
            add_header Content-Encoding gzip;
            gzip off;
            default_type application/wasm;
        }
        location ~ \.js\.gz$ {
            add_header Content-Encoding gzip;
            gzip off;
            default_type application/javascript;
        }
        location ~ \.data\.gz$ {
            add_header Content-Encoding gzip;
            gzip off;
            default_type application/octet-stream;
        }
        location ~ \.symbols\.json\.gz$ {
            add_header Content-Encoding gzip;
            gzip off;
            default_type application/octet-stream;
        }
        location ~ \.gz$ {
            add_header Content-Encoding gzip;
            gzip off;
            default_type application/octet-stream;
        }
    }
}
