name: Deploy Server

on:
  push:
    branches: [ main ]
    paths:
      - 'Server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Copy Server Files via SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "Server/*"
        target: "/home/${{ secrets.SERVER_USER }}/projects/HiddenGame/server" # Adjust destination path
        strip_components: 1

    - name: Restart PM2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ~/projects/HiddenGame/server
          npm install
          npm run build
          # Start if not running, otherwise restart
          pm2 describe hiddengame > /dev/null
          if [ $? -eq 0 ]; then
            # Assuming pm2 is tracking dist/server.js already. If not, this still restarts the instance.
            pm2 restart hiddengame
          else
            # First time startup pointing to the compiled typescript file
            pm2 start dist/server.js --name "hiddengame"
            pm2 save
          fi
